### ISSUE TITLE
Can't build using flutter 2.0 ~ 2.1

### ISSUE THREAD

**Issue by scris** [tomaschyly/tch_common_widgets#1]
See https://github.com/flutter/flutter/pull/77976, `color` of `CircularProgressIndicator` was introduced in 2.2, and `ButtonWidget.dart:154:23` uses `color`, therefore, this package was only suitable for flutter 2.2+, and maybe you should edit the version the package needed.

When building with flutter 2.0.2 for iOS, it says
```
../../../.pub-cache/hosted/../tch_common_widgets-0.6.14/lib/src/ui/buttons/ButtonWidget.dart:154:23: Error: No named parameter with the name 'color'.
                          color: iconColor,
                          ^^^^^
../../../flutter/packages/flutter/lib/src/material/progress_indicator.dart:542:9: Context: Found this candidate, but the arguments don't match.
      const CircularProgressIndicator({
            ^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by tomaschyly** [comment]
Yeah, forgot about that, I remember now, in the past having to handle it differently. 
Is there some reason you cannot use Flutter 2.2.x? We did not have any issues upgrading from 2.0.x to 2.2.x on our projects.
If its fine, I will update min Flutter version in pubspec only.

**Comment by tomaschyly** [comment]
I have updated the min version
